'use client';
/* oxlint-disable react/react-compiler -- Geometry buffers and shader uniforms are owned by the renderer. */
/**
 * The surrounding city: real Waterloo (OpenStreetMap) around the park, on the
 * same ground. Streets continue the park's paths, street trees carry its green
 * outward, and buildings are quiet massing with lit windows after dark. The
 * garden is where ideas live; the city is present but secondary.
 * Generated by scripts/park/build_context.mjs. Three draws in total.
 */
import { useEffect, useMemo, useRef, useState } from 'react';
import { useFrame, useThree } from '@react-three/fiber';
import * as THREE from 'three';
import { randomAt } from '@/lib/garden-visuals';
import type { ParkLook } from './look';

type Context = {
  quantum: number;
  buildings: { p: number[]; h: number; k?: number }[];
  roads?: { p: number[]; w: number }[];
  trees?: number[];
};

/** Shared ground for park and city, just below the park lawn (y ≈ 0.10). */
export const CITY_GROUND_Y = 0.07;
const ROAD_Y = CITY_GROUND_Y + 0.012;
/** A little height so low-rise streets still read at this distance. */
const EXAGGERATION = 1.3;
const noRaycast = () => {};
const color = new THREE.Color();

/** Items per slice: small enough that no slice noticeably blocks input. */
const SLICE = 350;

/** Wait for idle time (or the next frame where idle callbacks are unsupported). */
const idle = () =>
  new Promise<void>((resolve) =>
    'requestIdleCallback' in window
      ? requestIdleCallback(() => resolve(), { timeout: 400 })
      : setTimeout(resolve, 16),
  );

/** Run a sliced build during idle time; null if it was cancelled. */
async function runSliced<T>(
  build: Generator<void, T>,
  signal: AbortSignal,
): Promise<T | null> {
  for (;;) {
    const step = build.next();
    if (step.done) return step.value;
    await idle();
    if (signal.aborted) return null;
  }
}

/** Facade colours, blended toward each look's wall tone so every look stays coherent. */
const HOUSE_FACADES = [
  '#f1e6d2',
  '#e8d2b0',
  '#c56a4f',
  '#b9c4b3',
  '#e3cf9b',
  '#aebccb',
  '#efe8dc',
  '#d9a882',
];
const BLOCK_FACADES = [
  '#e9dcc5',
  '#d4c6ad',
  '#c4b49b',
  '#b5634a',
  '#aab3b6',
  '#d8d2c6',
  '#c99a6e',
];
const TOWER_FACADES = ['#a7b8c0', '#bcc5c7', '#d6d0c4', '#9fadb3'];
const FACADE_BLEND = 0.3;

/** Smallest edge-aligned rectangle around a footprint: centre, axes and size. */
function orientedBox(ring: THREE.Vector2[]) {
  let best = {
    area: Infinity,
    cx: 0,
    cz: 0,
    ux: 1,
    uz: 0,
    length: 0,
    width: 0,
  };
  for (let i = 0; i < ring.length; i++) {
    const a = ring[i],
      b = ring[(i + 1) % ring.length];
    const len = Math.hypot(b.x - a.x, b.y - a.y);
    if (!len) continue;
    const ux = (b.x - a.x) / len,
      uz = (b.y - a.y) / len;
    let minU = Infinity,
      maxU = -Infinity,
      minV = Infinity,
      maxV = -Infinity;
    for (const p of ring) {
      const u = p.x * ux + p.y * uz,
        v = -p.x * uz + p.y * ux;
      minU = Math.min(minU, u);
      maxU = Math.max(maxU, u);
      minV = Math.min(minV, v);
      maxV = Math.max(maxV, v);
    }
    const area = (maxU - minU) * (maxV - minV);
    if (area < best.area) {
      const u = (minU + maxU) / 2,
        v = (minV + maxV) / 2;
      best = {
        area,
        cx: u * ux - v * uz,
        cz: u * uz + v * ux,
        ux,
        uz,
        length: maxU - minU,
        width: maxV - minV,
      };
    }
  }
  // The ridge runs along the longer side.
  if (best.width > best.length)
    best = {
      ...best,
      ux: -best.uz,
      uz: best.ux,
      length: best.width,
      width: best.length,
    };
  return best;
}

function* buildBuildings(data: Context, look: ParkLook) {
  const q = data.quantum;
  const positions: number[] = [],
    normals: number[] = [],
    colors: number[] = [];
  const wall = new THREE.Color(look.city.walls),
    flat = new THREE.Color(look.city.flatRoof),
    roofs = look.city.roofs.map((c) => new THREE.Color(c));
  const vertex = (
    [x, y, z]: [number, number, number],
    n: [number, number, number],
    c: THREE.Color,
  ) => {
    positions.push(x, y, z);
    normals.push(...n);
    colors.push(c.r, c.g, c.b);
  };
  const base = new THREE.Color(),
    top = new THREE.Color(),
    roof = new THREE.Color(),
    facade = new THREE.Color();
  const palette = (list: string[]) =>
    list.map((c) => new THREE.Color(c).lerp(wall, FACADE_BLEND));
  const houses = palette(HOUSE_FACADES),
    blocks = palette(BLOCK_FACADES),
    towers = palette(TOWER_FACADES);
  /** A gable roof over a house's footprint box: two slopes and two gable ends. */
  const gableRoof = (
    box: ReturnType<typeof orientedBox>,
    y: number,
    c: THREE.Color,
  ) => {
    const overhang = 0.012,
      l = box.length / 2 + overhang,
      w = box.width / 2 + overhang,
      rise = Math.min(0.12, box.width * 0.5);
    const at = (u: number, v: number, h: number): [number, number, number] => [
      box.cx + box.ux * u - box.uz * v,
      y + h,
      box.cz + box.uz * u + box.ux * v,
    ];
    const face = (
      p: [number, number, number][],
      n: [number, number, number],
    ) => {
      for (const q of p) vertex(q, n, c);
    };
    const slope = Math.hypot(w, rise);
    for (const side of [1, -1]) {
      // Each slope's outward normal: across the ridge and up.
      const n: [number, number, number] = [
        (-box.uz * side * rise) / slope,
        w / slope,
        (box.ux * side * rise) / slope,
      ];
      const e1 = at(-l, side * w, 0),
        e2 = at(l, side * w, 0),
        r1 = at(-l, 0, rise),
        r2 = at(l, 0, rise);
      if (side === 1) face([e1, e2, r2, e1, r2, r1], n);
      else face([e2, e1, r1, e2, r1, r2], n);
    }
    for (const end of [1, -1]) {
      const n: [number, number, number] = [box.ux * end, 0, box.uz * end];
      const a = at(end * l, w, 0),
        b = at(end * l, -w, 0),
        r = at(end * l, 0, rise);
      if (end === 1) face([b, a, r], n);
      else face([a, b, r], n);
    }
  };
  for (let index = 0; index < data.buildings.length; index++) {
    if (index && index % SLICE === 0) yield;
    const b = data.buildings[index];
    const ring: THREE.Vector2[] = [];
    for (let i = 0; i < b.p.length; i += 2)
      ring.push(new THREE.Vector2(b.p[i] / q, b.p[i + 1] / q));
    if (ring.length < 3) continue;
    const y1 = CITY_GROUND_Y + (b.h / q) * EXAGGERATION;
    // Varied facades by kind and height; walls darken toward the ground.
    const choices = b.k ? houses : y1 > 0.55 ? towers : blocks;
    facade.copy(choices[Math.floor(randomAt(index, 14) * choices.length)]);
    const tone = 0.92 + randomAt(index, 11) * 0.12;
    top.copy(facade).multiplyScalar(tone);
    base.copy(facade).multiplyScalar(tone * 0.76);
    if (b.k)
      roof
        .copy(roofs[Math.floor(randomAt(index, 12) * roofs.length)])
        .multiplyScalar(0.9 + randomAt(index, 13) * 0.2);
    else roof.copy(flat).multiplyScalar(0.94 + randomAt(index, 13) * 0.08);
    for (let i = 0; i < ring.length; i++) {
      const a = ring[i],
        c = ring[(i + 1) % ring.length];
      const dx = c.x - a.x,
        dz = c.y - a.y,
        len = Math.hypot(dx, dz) || 1;
      // Rings are counter-clockwise in x/z, so this normal points outward.
      const n: [number, number, number] = [dz / len, 0, -dx / len];
      vertex([a.x, CITY_GROUND_Y, a.y], n, base);
      vertex([c.x, CITY_GROUND_Y, c.y], n, base);
      vertex([c.x, y1, c.y], n, top);
      vertex([a.x, CITY_GROUND_Y, a.y], n, base);
      vertex([c.x, y1, c.y], n, top);
      vertex([a.x, y1, a.y], n, top);
    }
    // Houses get pitched roofs; larger buildings keep flat roofs on their outline.
    const box = b.k ? orientedBox(ring) : null;
    if (box && box.width > 0.02 && box.length < 1.2) gableRoof(box, y1, roof);
    else
      for (const [i, j, k] of THREE.ShapeUtils.triangulateShape(ring, [])) {
        vertex([ring[i].x, y1, ring[i].y], [0, 1, 0], roof);
        vertex([ring[k].x, y1, ring[k].y], [0, 1, 0], roof);
        vertex([ring[j].x, y1, ring[j].y], [0, 1, 0], roof);
      }
  }
  return geometryFrom(positions, normals, colors);
}

/** Street ribbons with small joints so bends never gap. */
function* buildRoads(data: Context, look: ParkLook) {
  const q = data.quantum;
  const positions: number[] = [],
    normals: number[] = [],
    colors: number[] = [];
  const road = new THREE.Color(look.city.road);
  const quad = (points: [number, number][], c: THREE.Color) => {
    // Every triangle faces up. A back-facing one would have its normal flipped by
    // the double-sided material and be lit from below, showing as a pale patch.
    for (let t = 0; t + 2 < points.length; t += 3) {
      const a = points[t];
      let b = points[t + 1],
        d = points[t + 2];
      if ((b[1] - a[1]) * (d[0] - a[0]) - (b[0] - a[0]) * (d[1] - a[1]) < 0)
        [b, d] = [d, b];
      for (const [x, z] of [a, b, d]) {
        positions.push(x, ROAD_Y, z);
        normals.push(0, 1, 0);
        colors.push(c.r, c.g, c.b);
      }
    }
  };
  const list = data.roads ?? [];
  for (let index = 0; index < list.length; index++) {
    if (index && index % (SLICE * 3) === 0) yield;
    const r = list[index];
    const half = r.w / q / 2;
    // Major streets read a touch deeper than lanes and footpaths.
    const shade = color.copy(road).multiplyScalar(half > 0.18 ? 0.9 : 1);
    const pts: [number, number][] = [];
    for (let i = 0; i < r.p.length; i += 2)
      pts.push([r.p[i] / q, r.p[i + 1] / q]);
    for (let i = 0; i < pts.length - 1; i++) {
      const [ax, az] = pts[i],
        [bx, bz] = pts[i + 1];
      const len = Math.hypot(bx - ax, bz - az);
      if (!len) continue;
      const nx = (-(bz - az) / len) * half,
        nz = ((bx - ax) / len) * half;
      quad(
        [
          [ax + nx, az + nz],
          [bx - nx, bz - nz],
          [bx + nx, bz + nz],
          [ax + nx, az + nz],
          [ax - nx, az - nz],
          [bx - nx, bz - nz],
        ],
        shade,
      );
      if (i > 0) {
        // A hexagonal joint fills the wedge at each bend.
        for (let s = 0; s < 6; s++) {
          const t0 = (s / 6) * Math.PI * 2,
            t1 = ((s + 1) / 6) * Math.PI * 2;
          quad(
            [
              [ax, az],
              [ax + Math.cos(t1) * half, az + Math.sin(t1) * half],
              [ax + Math.cos(t0) * half, az + Math.sin(t0) * half],
            ],
            shade,
          );
        }
      }
    }
  }
  return geometryFrom(positions, normals, colors);
}

function geometryFrom(
  positions: number[],
  normals: number[],
  colors: number[],
) {
  const geometry = new THREE.BufferGeometry();
  geometry.setAttribute(
    'position',
    new THREE.Float32BufferAttribute(positions, 3),
  );
  geometry.setAttribute('normal', new THREE.Float32BufferAttribute(normals, 3));
  geometry.setAttribute('color', new THREE.Float32BufferAttribute(colors, 3));
  geometry.computeBoundingSphere();
  return geometry;
}

/**
 * Procedural lit windows on walls after dark: a storey grid (≈3.3 m) with a
 * stable hash choosing which rooms are lit. No textures or extra geometry.
 */
function useBuildingMaterial() {
  return useMemo(() => {
    const uniforms = { uNight: { value: 0 } };
    const material = new THREE.MeshStandardMaterial({
      vertexColors: true,
      roughness: 0.92,
    });
    material.onBeforeCompile = (shader) => {
      shader.uniforms.uNight = uniforms.uNight;
      shader.vertexShader =
        'varying vec3 vCityPos;\nvarying vec3 vCityNormal;\n' +
        shader.vertexShader.replace(
          '#include <begin_vertex>',
          '#include <begin_vertex>\nvCityPos=(modelMatrix*vec4(transformed,1.)).xyz;vCityNormal=normalize(mat3(modelMatrix)*objectNormal);',
        );
      shader.fragmentShader =
        'uniform float uNight;\nvarying vec3 vCityPos;\nvarying vec3 vCityNormal;\nfloat cityHash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}\n' +
        shader.fragmentShader
          .replace(
            '#include <color_fragment>',
            `#include <color_fragment>
if(abs(vCityNormal.y)<0.5){
  // By day the same window grid reads as glass, so facades aren't blank.
  vec2 facadeDay=vec2(abs(vCityNormal.x)>abs(vCityNormal.z)?vCityPos.z:vCityPos.x,vCityPos.y-${CITY_GROUND_Y.toFixed(2)});
  vec2 gridDay=facadeDay/vec2(0.1,0.11);vec2 fd=fract(gridDay);
  float paneDay=step(.28,fd.x)*step(fd.x,.72)*step(.32,fd.y)*step(fd.y,.76)*step(.5,floor(gridDay.y));
  diffuseColor.rgb=mix(diffuseColor.rgb,vec3(.36,.43,.48),paneDay*.6*(1.-uNight));
}`,
          )
          .replace(
            '#include <emissivemap_fragment>',
            `#include <emissivemap_fragment>
if(uNight>0.01&&abs(vCityNormal.y)<0.5){
  vec2 facade=vec2(abs(vCityNormal.x)>abs(vCityNormal.z)?vCityPos.z:vCityPos.x,vCityPos.y-${CITY_GROUND_Y.toFixed(2)});
  vec2 grid=facade/vec2(0.1,0.11);vec2 f=fract(grid);vec2 cell=floor(grid);
  float pane=step(.28,f.x)*step(f.x,.72)*step(.32,f.y)*step(f.y,.76)*step(.5,cell.y);
  float lit=step(.74,cityHash(cell+floor(vCityPos.xz*3.)*.37));
  totalEmissiveRadiance+=vec3(1.,.74,.44)*pane*lit*uNight*1.1;
}`,
          );
    };
    return { material, uniforms };
  }, []);
}

function StreetTrees({
  data,
  look,
  night,
}: {
  data: Context;
  look: ParkLook;
  night: THREE.Color;
}) {
  const ref = useRef<THREE.InstancedMesh>(null);
  const { invalidate } = useThree();
  const count = (data.trees?.length ?? 0) / 2;
  useEffect(() => {
    const mesh = ref.current;
    const trees = data.trees;
    if (!mesh || !trees) return;
    const o = new THREE.Object3D(),
      greens = look.city.trees;
    for (let i = 0; i < count; i++) {
      const x = trees[i * 2] / data.quantum,
        z = trees[i * 2 + 1] / data.quantum;
      const spread = 0.13 + randomAt(i, 21) * 0.07,
        height = 0.2 + randomAt(i, 22) * 0.12;
      o.position.set(x, CITY_GROUND_Y + height * 0.95, z);
      o.rotation.set(0, randomAt(i, 23) * Math.PI, 0);
      o.scale.set(spread, height, spread);
      o.updateMatrix();
      mesh.setMatrixAt(i, o.matrix);
      mesh.setColorAt(
        i,
        color.set(greens[Math.floor(randomAt(i, 24) * greens.length)]),
      );
    }
    mesh.instanceMatrix.needsUpdate = true;
    if (mesh.instanceColor) mesh.instanceColor.needsUpdate = true;
    invalidate();
  }, [data, look, count, invalidate]);
  if (!count) return null;
  return (
    <instancedMesh
      ref={ref}
      args={[undefined, undefined, count]}
      receiveShadow
      raycast={noRaycast}
    >
      <icosahedronGeometry args={[1, 0]} />
      <meshStandardMaterial flatShading roughness={0.9} color={night} />
    </instancedMesh>
  );
}

/** Seconds for the city to grow out of the ground after "Transform me". */
const RISE = 1.6;

export function CityContext({
  look,
  afterDark,
  rise = false,
  onReady,
}: {
  look: ParkLook;
  /** 0 in daylight rising to 1 at night: darkens massing and lights windows. */
  afterDark: number;
  /** Grow out of the ground once built, instead of appearing in place. */
  rise?: boolean;
  /** Called once the city is shown, or has failed to load. */
  onReady?: () => void;
}) {
  const { invalidate } = useThree();
  const group = useRef<THREE.Group>(null);
  // Read once: only the mount that follows a transform should animate.
  const rising = useRef(rise);
  const riseStart = useRef<number | null>(null);
  const ready = useRef(onReady);
  ready.current = onReady;
  const buildingMaterial = useBuildingMaterial();
  const [data, setData] = useState<Context | null>(null);
  useEffect(() => {
    // Context is optional atmosphere: load it after the park, and fail quietly.
    const controller = new AbortController();
    fetch('/park/context.json', { signal: controller.signal })
      .then((r) => (r.ok ? (r.json() as Promise<Context>) : null))
      .then((json) => {
        if (json) setData(json);
        else ready.current?.();
      })
      .catch(() => {
        // An abort means this effect was torn down, not that the city failed.
        if (!controller.signal.aborted) ready.current?.();
      });
    return () => controller.abort();
  }, []);
  // Geometry is built in idle-time slices so the city never delays the park,
  // the first taps, or the ideas and loves loading alongside it.
  const [geometry, setGeometry] = useState<{
    buildings: THREE.BufferGeometry;
    roads: THREE.BufferGeometry;
  } | null>(null);
  useEffect(() => {
    if (!data) return;
    const controller = new AbortController();
    void (async () => {
      try {
        const buildings = await runSliced(
          buildBuildings(data, look),
          controller.signal,
        );
        const roads =
          buildings &&
          (await runSliced(buildRoads(data, look), controller.signal));
        if (buildings && roads) {
          setGeometry({ buildings, roads });
          ready.current?.();
        } else {
          buildings?.dispose();
          roads?.dispose();
        }
      } catch {
        // Malformed context data: the park stays usable, and "Transform me" finishes.
        if (!controller.signal.aborted) ready.current?.();
      }
    })();
    return () => controller.abort();
  }, [data, look]);
  useEffect(
    () => () => {
      geometry?.buildings.dispose();
      geometry?.roads.dispose();
    },
    [geometry],
  );
  const buildings = geometry?.buildings,
    roads = geometry?.roads;
  useEffect(
    () => () => buildingMaterial.material.dispose(),
    [buildingMaterial],
  );
  // Colours are baked per vertex; after dark a shared multiplier dims the city.
  const night = useMemo(
    () =>
      new THREE.Color('#ffffff').lerp(
        new THREE.Color('#454c66'),
        afterDark * 0.85,
      ),
    [afterDark],
  );
  useEffect(() => {
    buildingMaterial.material.color.copy(night);
    buildingMaterial.uniforms.uNight.value = afterDark;
    invalidate(); // demand rendering: a uniform change alone requests no frame
  }, [buildingMaterial, night, afterDark, invalidate]);
  useFrame(({ clock }) => {
    const city = group.current;
    if (!city || !rising.current) return;
    riseStart.current ??= clock.elapsedTime;
    const t = Math.min(1, (clock.elapsedTime - riseStart.current) / RISE);
    city.scale.y = Math.max(0.001, 1 - (1 - t) ** 3);
    if (t < 1) invalidate();
    else rising.current = false;
  });
  useEffect(() => {
    if (buildings && rising.current) invalidate();
  }, [buildings, invalidate]);
  if (!data || !buildings || !roads) return null;
  return (
    <group ref={group} scale-y={rising.current ? 0.001 : 1}>
      <mesh geometry={roads} receiveShadow raycast={noRaycast}>
        {/* Flat ribbons: draw both faces so winding can never hide a street. */}
        <meshStandardMaterial
          vertexColors
          roughness={1}
          color={night}
          side={THREE.DoubleSide}
          polygonOffset
          polygonOffsetFactor={-1}
          polygonOffsetUnits={-1}
        />
      </mesh>
      {/* Receives the park's shadows but casts none: as one mesh it would
          redraw the whole city in every shadow pass. */}
      <mesh
        geometry={buildings}
        material={buildingMaterial.material}
        receiveShadow
        raycast={noRaycast}
      />
      <StreetTrees data={data} look={look} night={night} />
    </group>
  );
}
